### ISSUE TITLE
Request: update code to latest version of alpaca-trade-api

### ISSUE THREAD

**Issue by sanzgiri** [Harkishan-99/Alternative-Bars#1]
Hi,

The code runs fine with alpaca-trade-api v0.42 but not with the latest version (0.51). I don't see any errors, but no data gets pulled.

Thanks,
Ashutosh

**Comment by Harkishan-99** [comment]
Hi @sanzgiri . 

You are right, for some reason, v0.51 doesn't stream data and the overall version was kind of unstable. That's the reason I went with the specific version (v0.42). I have discussed the issue with Alpaca's team and the problem should be solved in the latest release.
